version: 1.0
applications:
  - appRoot: .
    env:
      variables:
        APP_ID: d2wwjdgjliumng
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
            - npx ampx -v
            - npx ampx pipeline-deploy --app-id $APP_ID --branch $AWS_BRANCH
            - node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('amplify_outputs.json','utf8'));const url=(p.custom&&p.custom.STUDENT_API_BASE)||'';console.log('FUNCTION_URL='+url);fs.writeFileSync('function_url.txt',url);" || true
            - FUNCTION_URL=$(cat function_url.txt 2>/dev/null || true)
            - echo "FUNCTION_URL=$FUNCTION_URL"
            - sed -i "s|window.STUDENT_API_BASE.*|window.STUDENT_API_BASE = '${FUNCTION_URL}';|" src/index.html || true
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: dist/SchoolLink
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
